useTabs: false
singleQuote: true
trailingComma: all

plugins:
  - prettier-plugin-pkg

overrides:
  - files:
      - .vscode/*.json
    options:
      parser: jsonc
  - files:
      - .hintrc
    options:
      parser: json
