[pre-commit]
parallel = true

[pre-commit.commands.biome]
run = "npx biome check --apply --no-errors-on-unmatched --files-ignore-unknown=true {staged_files} && git update-index --again"
glob = "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"

[pre-commit.commands.prettier]
run = "npx prettier --write {staged_files}"
glob = "*.{css,yml,uaml,md,html}"
